### PR TITLE
update passport-oauth2 pkg

### PR DESCRIPTION
**Pull request by RobDolares**
related issue: https://github.com/open-cluster-management/backlog/issues/16636
Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>

### CODE REVIEW

**Review by ycao56 — APPROVED** [review]

**Review by dhaiducek — APPROVED** [review]

**Comment by ycao56** [comment]
@RobDolares I assume you will also publish a new version to npm registry and bump the version in grc-ui.

**Pull request merged**
